resolver: lts-5.17
# resolver: lts-6.2

packages:
- .

- ../spiros
- ../NSSpeechRecognizer
- ../commands-core
- ../derive-monoid
- ../s-expression

extra-deps:

- spiros-0.0.0
- NSSpeechRecognizer-0.0.0
- commands-core-0.0.0
- derive-monoid-0.0.0
- s-expression-0.0.0

- language-python-0.5.2
- c-storable-deriving-0.1.3
